import { ObjectId } from 'mongodb';
import { Quote, QuoteType } from '../src/lib/type';

export const quoteSmall: Quote[] = [
  {
    _id: new ObjectId(),
    quote: "I think therefore I am",
    author: "René Descartes",
    category: "philosophy",
    period: 1500,
    image: "https://res.cloudinary.com/drewpager/image/upload/v1586180957/enlighten-me-daily/eq5dilfw9t3hjsquicmc.jpg",
    type: QuoteType.Quote
  },
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
{_id: new ObjectId(), quote:"There is joy in work. There is no happiness except in the realization that we have accomplished something.",author:"Henry Ford",category:"motivation", period:1920,image:"https://res.cloudinary.com/drewpager/image/upload/v1586790374/enlighten-me-daily/uaq1dsd0cbushvdqjjpx.jpg",type:QuoteType.Quote},
];