require("dotenv").config();

import { ObjectId } from 'mongodb';
import { connectDatabase } from '../src/database';
import { Quote, QuoteType, User, Bookmarking } from '../src/lib/type';

const seed = async () => {
  try {
    console.log(`[seed]: attempting to seed the database`)

    const db = await connectDatabase();
    const quotes: Quote[] = [
      {
        _id: new ObjectId(),
        quote: "I think therefore I am",
        author: "René Descartes",
        category: "philosophy",
        period: 1500,
        image: "https://images.unsplash.com/photo-1509029032154-54ba8b3216d4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80",
        type: QuoteType.Quote
      },
      {
        _id: new ObjectId(),
        quote: "Slow is smooth and smooth is fast",
        author: "US Military Adage",
        category: "philosophy",
        period: 1900,
        image: "https://images.unsplash.com/photo-1508530786855-dfea35260b8d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80",
        type: QuoteType.Quote
      },
      {
        _id: new ObjectId(), 
        quote: "Do, or do not. There is no try.",
        author: "Yoda",
        category: "philosophy",
        period: 1980,
        image: "https://images.unsplash.com/photo-1514050566906-8d077bae7046?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1352&q=80g",
        type: QuoteType.Quote
      },
      {
        _id: new ObjectId(),
        quote: "Goals are the fuel in the furnace of achievement.",
        author: "Brian Tracy",
        category: "motivation",
        period: 2000,
        image: "https://images.unsplash.com/photo-1514050566906-8d077bae7046?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1352&q=80",
        type: QuoteType.Quote
      },
      {
        _id: new ObjectId(),
        quote:"Leadership is not about a title or a designation. It's about impact, influence and inspiration. Impact involves getting results, influence is about spreading the passion you have for your work, and you have to inspire teammates and customers.",
        author:'Robin S. Sharma',
        category:'leadership',
        period: 2,
        image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',
        type:QuoteType.Quote
      },
      {
        _id:new ObjectId(),
        quote:'The supreme quality for leadership is unquestionably integrity. Without it, no real success is possible, no matter whether it is on a section gang, a football field, in an army or in an office.',
        author:'Dwight D. Eisenhower',
        category:'leadership',
        period:3,
        image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',
        type:QuoteType.Quote
      },
      {
        _id:new ObjectId(),
        quote:'A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say; we did it ourselves.',
        author:'Lao Tzu',
        category:'leadership',
        period:4,
        image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',
        type:QuoteType.Quote
      },
      {
        _id:new ObjectId(),
        quote:"Ultimately, leadership is not about glorius crowning acts. It's about keeping your team focused on a goal and motivated to do their best to achieve it, especially when the stakes are high and the consequences really matter. It is about laying the groundwork for others' success, and then standing back and letting them shine.",
        author:'Chris Hadfield',
        category:'leadership',
        period:5,
        image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',
        type:QuoteType.Quote
      },
      {_id:new ObjectId(),quote:"Leadership is not about you; it's about investing in the growth of others.",author:'Ken Blanchard',category:'leadership',period:6,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is about vision and responsibility, not power.',author:'Seth Berkley',category:'leadership',period:7,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Men make history and not the other way around. In periods where there is no leadership, society stands still. Progress occurs when courageous, skillful leaders seize the opportunity to change things for the better.',author:'Harry S. Truman',category:'leadership',period:8,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is a way of thinking, a way of acting and, most importantly, a way of communicating.',author:'Simon Sinek',category:'leadership',period:9,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'A leader is one who knows the way, goes the way, and shows the way.',author:'John C. Maxwell',category:'leadership',period:10,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is solving problems. The day soldiers stop bringing you their problems is the day you have stopped leading them. They have either lost confidence that you can help or concluded you do not care. Either case is a failure of leadership',author:'Colin Powell',category:'leadership',period:11,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'It is better to lead from behind and to put others in front, especially when you celebrate victory when nice things occur. You take the front line when there is danger. Then people will appreciate your leadership',author:'Nelson Mandella',category:'leadership',period:12,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'The secret to success is good leadership, and good leadership is all about making the llives of your team members or workers better.',author:'Tony Dungy',category:'leadership',period:13,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'People ask the difference between a leader and a boss. The leader leads, and the boss drives.',author:'Theodore Roosevelt',category:'leadership',period:14,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'The greatest gift of leadership is a boss who wants you to be successful.',author:'Jon Taffer',category:'leadership',period:15,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'I know of no single formula for success. But over the years I have observed that some attributes of leadership are universal and are often about finding ways of encouraging people to combine their efforts, their talents, their insights, their enthusiasm and their inspiration to work together.',author:'Queen Elizabeth II',category:'leadership',period:16,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is having a compelling vision, a comprehensive plan, relentless implementation and talented people working together.',author:'Alan Mulally',category:'leadership',period:17,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Leadership contains certain elements of good management, but it requires that you inspire, that you build durable trust. For an organization to be not just good but to win, leadership means evoking participation larger than the job description, commitment deeper than any job contract's wording.",author:'Stanley A. McChrystal',category:'leadership',period:18,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Practice self-awareness, self-evaluation, and self-improvement. If we are aware that our manners, language, behavior and actions are measured against our values and principles, we are able to more easily embody the philosophy, leadership is a matter of how to be, not how to do.',author:'Frances Hesselbein',category:'leadership',period:19,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership and learning are indispensable to each other.',author:'John F. Kennedy',category:'leadership',period:20,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Good leadership consists of showing average people how to do the work of superior people.',author:'John D. Rockefeller',category:'leadership',period:21,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'No man will make a great leader who wants to do it all himself or get all the credit for doing it.',author:'Andrew Carnegie',category:'leadership',period:22,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Leadership is not a popularity contest; it's about leaving your ego at the door. The name of the game is to lead without a title.",author:'Robin S. Sharma',category:'leadership',period:23,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"The task of the leader is to get his people from where they are to where they have not been.",author:'Henry Kissinger',category:'leadership',period:24,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Outstanding leaders go out of their way to boost the self-esteem of their personnel. If people believe in themselves, it's amazing what they can accomplish.",author:'Sam Walton',category:'leadership',period:25,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Effective leadership is not about making speeches or being liked; leadership is defined by results not attributes.',author:'Peter Drucker',category:'leadership',period:26,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'A good leader takes a little more than his share of the blame, a little less than his share of the credit.',author:'Arnold H. Glasow',category:'leadership',period:27,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Good management is the art of making problems so interesting and their solutions so constructive that everyone wants to get to work and deal with them.',author:'Paul Hawken',category:'leadership',period:28,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Whether we're talking about leadership, teamwork, or client service, there is no more powerful attribute than the ability to be genuinely honest about one's weaknesses, mistakes and needs for help.",author:'Patrick Lencioni',category:'leadership',period:29,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is a privilege to better the lives of others. It is not an opportunity to satisfy personal greed.',author:'Mwai Kibaki',category:'leadership',period:30,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'The quality of a leader is reflected in the standards they set for themselves.',author:'Ray Kroc',category:'leadership',period:31,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Effective leadership is putting first things first. Effective management is discipline, carrying it out.',author:'Stephen Covey',category:'leadership',period:32,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Leadership is unlocking people's potential to become better.",author:'Bill Bradley',category:'leadership',period:33,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is a potent combination of strategy and character. But if you must be without one, be without the strategy.',author:'Norman Schwarzkopf',category:'leadership',period:34,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Management is efficiency in climbing the ladder of success; leadership determines whether the ladder is leaning against the right wall.',author:'Stephen Covey',category:'leadership',period:35,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'It is better to have a lion at the head of an army of sheep, than a sheep at the head of an army of lions.',author:'Daniel Defoe',category:'leadership',period:36,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is the art of getting someone else to do something you want done because he wants to do it.',author:'Dwight D. Eisenhower',category:'leadership',period:37,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is the capacity to translate vision into reality.',author:'Warren Bennis',category:'leadership',period:38,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is a choice, not a position.',author:'Stephen Covey',category:'leadership',period:39,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'A genuine leader is not a searcher for consensus but a molder of consensus.',author:'Martin Luther King, Jr.',category:'leadership',period:40,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Enlightened leadership is spiritual if we understand spirituality not as some kind of religious dogma or ideology but as the domain of awareness where we experience values like truth, goodness, beauty, love and compassion, and also intuition, creativity, insight and focused attention.',author:'Deepak Chopra',category:'leadership',period:41,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'The world needs new leadership, but the new leadership is about working together.',author:'Jack Ma',category:'leadership',period:42,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'No matter how good you think you are as a leader, my goodness, the people around you will have all kinds of ideas for how you can get better. So for me, the most fundamental thing about leadership is to have the humility to continue to get feedback and to try to get better - because your job is to try to help everrybody else get better.',author:'Jim Yong Kim',category:'leadership',period:43,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is inspiring people. Management is keeping the trains running on time.',author:'Andy Dunn',category:'leadership',period:44,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Management is about arranging and telling. Leadership is about nurturing and enhancing.',author:'Tom Peters',category:'leadership',period:45,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"One of the best paradoxes of leadership is a leader's need to be both stubborn and open-minded. A leader must insist on sticking to the vision and stay on course to the destination. But he must be open-minded during the process.",author:'Simon Sinek',category:'leadership',period:46,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is not a basket of tricks or strategies or skills that you pull out. Leadership begins with the quality of the person.',author:'Frances Hesselbein',category:'leadership',period:47,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"One of the topics I'm most passionate about is servant leadership -- the greatest leaders recognize that they're here to serve, not to be served.",author:'Ken Blanchard',category:'leadership',period:48,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"I've learned that positive thinking and encouragement are essential for leadership and progress.",author:'Richard M. DeVos',category:'leadership',period:49,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Millions saw the apple fall, but Newton was the one who asked why.',author:'Bernard Baruch',category:'leadership',period:50,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"I've learned that leadership is about falling in love with the people and the people falling in love with you. It is about serving the people with selflessness, with sacrifice, and with the need to put the common good ahead of personal interests.",author:'Joyce Banda',category:'leadership',period:51,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership to me means duty, honor, country. It means character, and it means listening from time to time.',author:'George W. Bush',category:'leadership',period:52,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"In this age, I don't care how tactically or operationally brilliant you are: if you cannot create harmony--even vicious harmony--on the battlefield based on trust across service lines, across coalition and national lines, and across civilian/military lines, you need to go home, because your leadership is obsolete.",author:'Jim Mattis',category:'leadership',period:53,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'The test of leadership is not to put greatness into humanity, but to elicit it, for the greatness is already there.',author:'James Buchanan',category:'leadership',period:54,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"To me, leadership is about encouraging people. It's about stimulating them. It's about enabling them to achieve what they can achieve--and to do that with a purpose.",author:'Christine Lagarde',category:'leadership',period:55,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'I suppose leadership at one time meant muscles; but today it means getting along with people.',author:'Mahatma Gandhi',category:'leadership',period:56,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"There's two parts of leadership. You've got to be a good leader--you've got to be somebody that people want to emulate and care about the other people. But the other guys that you have have to accept your leadership. They have to respond to it. That's the chemistry that you never know how that is going to happen.",author:'Nick Saban',category:'leadership',period:57,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Making good decisions is a crucial skill at every level.',author:'Peter Drucker',category:'leadership',period:58,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"If a window of opportunity appears, don't pull down the shade.",author:'Tom Peters',category:'leadership',period:59,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is hard to define and good leadership even harder. But if you can get people to follow you to the ends of the earth, you are a great leader.',author:'Indra Nooyi',category:'leadership',period:60,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Every time you have to speak, you are auditioning for leadership.',author:'James Humes',category:'leadership',period:61,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is working with goals and vision; management is working with objectives.',author:'Russel Honore',category:'leadership',period:62,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Leadership is a mindset in action. So don't wait for the title. Leadership isn't something that anyone can give you--you have to earn it and claim it for yourself.",author:'Travis Bradberry',category:'leadership',period:63,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'We are looking for a set of personal characteristics that predict success, the first and foremost of which is perseverance in the face of challenges. We also look for the ability to influence and motivate others who share your values, strong problem-solving ability, and leadership.',author:'Wendy Kopp',category:'leadership',period:64,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Leadership is a mindset in action. So don't wait for the title. Leadership isn't something that anyone can give you--you have to earn it and claim it for yourself.",author:'Travis Bradberry',category:'leadership',period:65,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership flows from inner character and integrity of ambition, which inspires others to lend themselves to your organizations"s mission.',author:'Frances Hesselbein',category:'leadership',period:66,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'An important part of leadership is being able to hold two things in your mind at once: Dealing with the reality, whatever it may be, and focusing on hope for the future. Any leader helping an organization through challenges needs to be able to do both.',author:'Alan Mulally',category:'leadership',period:67,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"I think the currency of leadership is transparency. You've got to be truthful. I don't think you should be vulnerable every day, but there are moments where you've got to share your soul and conscience with people and show them who you are, and not be afraid of it.",author:'Howard Schultz',category:'leadership',period:68,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Success is no longer about changing strategies more often, but having the agility to execute multiple strategies concurrently. And success requires CEOs to develop the right leadership capabilities, workforce skills, and corporate cultures to support digital transformation.',author:'Pierre Nanterme',category:'leadership',period:69,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"My mother was in the Army Reserve for six years. She taught me the importance of following rules, finishing what I start, never giving up, leadership skills, teamwork, staying positive, motivated and how to pack the military way when I'm traveling!",author:'Laurie Hernandez',category:'leadership',period:70,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'I think one of the keys to leadership is recognizing that everybody has gifts and talents. A good leader will learn how to harness those gifts toward the same goal.',author:'Ben Carson',category:'leadership',period:71,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'The functioin of leadership is to produce more leaders, not more followers.',author:'Ralph Nader',category:'leadership',period:72,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Where there is no vision, there is no hope.',author:'George Washington Carver',category:'leadership',period:73,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'The key to being a good manager is keeping the people who hate me away from those who are still undecided.',author:'Casey Stengel',category:'leadership',period:74,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is about being a servant first.',author:'Allen West',category:'leadership',period:75,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Honor bespeaks worth. Confidence begets trust. Service brings satisfaction. Cooperation proves the quality of leadership.',author:'James Cash Penney',category:'leadership',period:76,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'No institution can possibly survive if it needs geniuses or supermen to manage it. It must be organized in such a way as to be able to get along under a leadership composed of average human beings.',author:'Peter Drucker',category:'leadership',period:77,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Empowerment isn't a buzzword among leadership gurus. It's a proven technique where leaders give their teams the appropriate training, tools, resources and guidance to succeed.",author:'John Rampton',category:'leadership',period:78,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Most businesses think that product is the most important thing, but without great leadership, mission and a team that deliver results at a high level, even the best product won't make a company successful.",author:'Robert Kyosaki',category:'leadership',period:79,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Leadership is a matter of having people look at you and gain confidence, seeing how you react. If you're in control, they're in control.",author:'Tom Landry',category:'leadership',period:80,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'I am humble enough to understand there are many people who know much more than I do on many subjects, so I listen to them. Integrity is also critical to leadership, so I believe there must always be alignment between what you think, say and do.',author:'Ajay Piramal',category:'leadership',period:81,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"The one thing I have learned as a CEO is that leadership at various levels is vastly different. When I was leading a function or a business, there were certain demands and requirements to be a leader. As you move up the organization, the requirements for leading that organization don't grow vertically; they grow exponentially.",author:'Indra Nooyi',category:'leadership',period:82,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"If you want to get the most out of your men, give them a break! Don't make them work completely in the dark. If you do, they won't do a bit more than they have to. But if they comprehend, they'll work like mad.",author:'Chesty Puller',category:'leadership',period:83,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Whether you empower one person or the free world, that is leadership.',author:'Julie Foudy',category:'leadership',period:84,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Leaders of the future will have to be visionary and be able to bring people in--real comunicators. These are things that women bring to leadership and executive positions, and it's going to be incredibly valuable and increadibly in demand.",author:'Anita Borg',category:'leadership',period:85,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"I think to be a great quarterback, you have to have a great leadership, great attention to detail, and a relentless competitive nature. And that's what I try to bring to the table, and I have a long way to go. I'm still learning, and I'm still on a constant quest for knowledge.",author:'Russell Wilson',category:'leadership',period:86,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"I think leadership is more than just being able to cross the t's and dot the i's. It's about character and integrity and work ethic.",author:'Steve Largent',category:'leadership',period:87,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is service to others',author:'Denise Morrison',category:'leadership',period:88,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is all about emotional intelligence. Management is taught, while leadership is experienced.',author:'Rajeev Suri',category:'leadership',period:89,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is more about clarity than it is about control',author:'Mark Goulston',category:'leadership',period:90,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is an opportunity to serve. It is not a trumpet call to self-importance.',author:'J. Donald Walters',category:'leadership',period:91,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'He who is prudent and lies in wait for an enemy who is not, will be victorious.',author:'Sun Tzu',category:'leadership',period:92,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership is loud. It is quiet. It is thoughtful and emotional and cerebral and nerdy and goofy and joyful and motivating.',author:'Julie Foudy',category:'leadership',period:93,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership comes in small acts as well as bold strokes.',author:'Carly Fiorina',category:'leadership',period:94,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"One of my beliefs about leadership is it's not how many followers you have, but how many people you have with different opinions that you can bring together and try to be a good listener.",author:'Robert Kraft',category:'leadership',period:95,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Leadership is something you earn, something you're chosen for. You can't come in yelling, 'I'm your leader!' If it happens, it's because the other guys respect you.",author:'Ben Roethlisberger',category:'leadership',period:96,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"I think you need to be intentional at times about your leadership--where you're eating lunch, who you're interacting with, making guys feel like you're interested in what they're doing. If it's authentic, then it's going to be an easy conversation and easy hangout time.",author:'Aaron Rodgers',category:'leadership',period:97,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"I don't subscribe to, 'Here are the top ten tips to successful leadership,' or, 'How to learn leadership in ten minutes.' A leader is someone who gives positive energy to others which then results in a better change than would have happened. I think everyone is a leader.",author:'Paul Polman',category:'leadership',period:98,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'No matter how carefully you plan your goals they will never be more than pipe dreams unless you pursue them with gusto.',author:'W. Clement Stone',category:'leadership',period:99,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"You're only as good as the people you hire.",author:'Ray Kroc',category:'leadership',period:100,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'I have a different vision of leadership. A leader is someone who brings people together.',author:'George W. Bush',category:'leadership',period:101,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership consists not in degrees of technique but in traits of character; it requires moral rather than athletic or intellectual effort, and it imposes on both leader and follower alike the burdens of self-restraint.',author:'Lewis H. Lapham',category:'leadership',period:102,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'One of the sad truths about leadership is that, the higher up the ladder you travel, the less you know.',author:'Margaret Heffernan',category:'leadership',period:103,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'A leader does not deserve the name unless he is willing to occasionally to stand alone.',author:'Henry Kissinger',category:'leadership',period:104,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"I have yet to meet members of a leadership team who I thought lacked the intelligence or the domain expertise required to be successful. I've met many, however, who failed to foster organizational health. Their companies were riddled with politics, various forms of dysfunction and general confusion about their direction and mission.",author:'Patrick Lencioni',category:'leadership',period:105,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"For any movement to gain momentum, it must start with a small action. This action becomes multiplied by the masses, and is made tangible when leadership changes course due to the weight of the movement's voice.",author:'Adam Braun',category:'leadership',period:106,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'But the person who scored well on an SAT will not necessarily be the best doctor or the best lawyer or the best businessman. These tests do not measure character, leadership, creativity, perseverance.',author:'William Julius Wilson',category:'leadership',period:107,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"A leadership culture is one where everyone thinks like an owner, a CEO or a managing director. It's one where everyone is entrepreneurial and proactive.",author:'Robin S. Sharma',category:'leadership',period:108,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'It is the responsibility of leadership to provide opportunity, and the responsibility of individuals to contribute.',author:'William Pollard',category:'leadership',period:109,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"When the best leader's work is done the people say, 'We did it ourselves.'",author:'Lao Tzu',category:'leadership',period:110,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"High expectations are the key to everything.",author:'Sam Walton',category:'leadership',period:111,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Constant, gentle pressure is my preferred technique for leadership, guidance and coaching.",author:'Danny Meyer',category:'leadership',period:112,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"How we think shows through in how we act. Attitude are mirrors of the mind. They reflect thinking.",author:'David Joseph Schwartz',category:'leadership',period:113,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Few things kill likeability as quickly as arrogance. Likable leaders don't act as though they're better than you because they don't think that they're better than you. Rather than being a source of prestige, they see their leadership position as bringing them additional accountability for serving those who follow them.",author:'Travis Bradberry',category:'leadership',period:114,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Showing leadership doesn't mean every employee will run the organization; that would lead to chaos. Businesses do need someone to set the vision and then lead the team to it.",author:'Robin S. Sharma',category:'leadership',period:115,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'A good objective of leadership is to help those who are doing poorly to do well and to help those who are doing well to do even better.',author:'Jim Rohn',category:'leadership',period:116,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"My role at Lockheed Martin puts me in contact with extraordinary leaders in many fields--from science and engineering to philanthropy and government. And since we also work closely with our nation's armed forces, we tend to reflect a lot on leadership and how we can inspire successful teamwork, cooperation and partnerships.",author:'Marillyn Hewson',category:'leadership',period:117,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Leadership is getting players to believe in you. If you tell a teammate you're ready to play as tough as you're able to, you'd better go out there and do it. Players will see right through a phony. And they can tell when you're not giving it all you've got.",author:'Larry Bird',category:'leadership',period:118,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Character in leadership is the most important balance for leadership. Without character, leaders have no safety. Leadership has no protection without character.',author:'Myles Munroe',category:'leadership',period:119,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Absolute identity with one's cause is the first and great condition of successful leadership.",author:'Woodrow Wilson',category:'leadership',period:120,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'The highest calling of leadership is to challenge the status quo and unlock the potential of others. We need a leader who will lead the resurgence of this great nation and unlock its potential once again.',author:'Carly Fiorina',category:'leadership',period:121,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'I think leadership is service and there is power in that giving: to help people, to inspire and motivate them to reach their fullest potential.',author:'Denise Morrison',category:'leadership',period:122,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"The very essence of leadership is that you have to have vision. You can't blow an uncertain trumpet.",author:'Theodore Hesburgh',category:'leadership',period:123,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"Leadership does not depend on being right.",author:'Ivan Illich',category:'leadership',period:124,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'My number one philosophy for leadership is leadership by example. If you are not willing to do it yourself, how can you show others how to do it?',author:'Linda McMahon',category:'leadership',period:125,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"I was raised with traditional stories of leadership: Robert E. Lee, John Buford at Gettysburg. And I also was raised with personal examples of leadership. This was my father in Vietnam. And I was raised to believe that soldiers were strong and wise and brave and faithful; they didn't lie, cheat, steal or abandon their comrades.",author:'Stanley A. McChrystal',category:'leadership',period:126,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'One secret of leadership is that the mind of a leader never turns off. Leaders even when they are sightseers or spectators, are active; not passive observers.',author:'James Humes',category:'leadership',period:127,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"I think leadership is not something you learn; it's something you discover.",author:'Myles Munroe',category:'leadership',period:128,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Great entrepreneurial DNA is comprised of leadership, technological vision, frugality and the desire to succeed.',author:'Steve Blank',category:'leadership',period:129,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'As a business owner, leadership is more than just telling others what to do. Leadership is about the investment we make into others and the responsibilities we accept for being the voice and direction that others count on.',author:'Lewis Howes',category:'leadership',period:130,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Leadership cannot really be taught. It can only be learned.',author:'Harold S. Geneen',category:'leadership',period:131,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"I don't know any other way to lead but by example.",author:'Don Shula',category:'leadership',period:132,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"We're trained to see the world in terms of charismatic organizations and charismatic people. That's who we look to for leadership and change, for transformation. We're awaiting the next J.F.K., the next Martin Luther King, the next Gandhi, the next Nelson Mandela.",author:'Paul Hawken',category:'leadership',period:133,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"If you command wisely, you'll be obeyed cheerfully.",author:'Thomas Fuller',category:'leadership',period:134,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'You were born to lead as mothers and fathers, because nowhere is righteous leadership more crucial than in the family.',author:'Sheri L. Dew',category:'leadership',period:135,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"You have to enable and empower people to make decisions independent of you. As I've learned, each person on a team is an extension of your leadership; if they feel empowered by you they will magnify your power to lead.",author:'Tom Ridge',category:'leadership',period:136,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:"I am endlessly fascinated that playing football is considered a training ground for leadership, but raising children isn't. Hey, it made me a better leader: you have to take a lot of people's needs into account; you have to look down the road. Trying to negotiate getting a couple of kids to watch the same TV show requires serious diplomacy.",author:'Dee Dee Myers',category:'leadership',period:137,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'True leadership lies in guiding others to success. In ensuring that everyone is performing at their best, doing the work they are pledged to do and doing it well.',author:'Bill Owens',category:'leadership',period:138,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Inability to make decisions is one of the principal reasons executives fail. Deficiency in decision-making ranks much higher than lack of specific knowledge or technical know-how as an indicator of leadership failure.',author:'John C. Maxwell',category:'leadership',period:139,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'The amount of good luck coming your way depends on your willingness to act.',author:'Barbara Sher',category:'motivation',period:140,image:'https://images.unsplash.com/photo-1504805572947-34fad45aed93?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'Be the chief but never the lord.',author:'Lao Tzu',category:'leadership',period:141,image:'https://images.unsplash.com/photo-1533511627347-4d1b893e1ad9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2044&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'No wind serves him who addresses his voyage to no certain port.',author:'Michel de Montaigne',category:'motivation',period:142,image:'https://images.unsplash.com/photo-1504805572947-34fad45aed93?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80',type:QuoteType.Quote},
      {_id:new ObjectId(),quote:'We are what we repeatedly do. Excellence, then, is not an act but a habit.',author:'Aristotle',category:'motivation',period:143,image:'https://images.unsplash.com/photo-1504805572947-34fad45aed93?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80',type:QuoteType.Quote},
    ];

    const bookmarkings: Bookmarking[] = [
      {
        _id: new ObjectId(),
        quote: {
          _id: new ObjectId(), 
          quote: "Goals are the fuel in the furnace of achievement.",
          author: "Brian Tracy",
          category: "motivation",
          period: 2000,
          image: "https://images.unsplash.com/photo-1514050566906-8d077bae7046?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1352&q=80",
          type: QuoteType.Quote
        },
        user: "5d398db94e84753160e08b51"
      }
    ]

    const users: User[] = [
      {
        _id: "5d378db94e84753170e08b55",
        token: "token_************",
        name: "Jimmy Johns",
        avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80",
        contact: "jimmy.j.johns@yahoo.com",
        bookmarkings: [],
        quotes: [
          new ObjectId("5d378db94e84753161e08b30"),
          new ObjectId("5d378db94e84753170e08b4a"),
          new ObjectId("5d378db94e84753160e18b4d")
        ]
      },
      {
        _id: "5d378db94e84753160e08b51",
        token: "token_************",
        name: "Leslie Pierce",
        avatar: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80",
        contact: "leslie.pierce@yahoo.com",
        bookmarkings: [],
        quotes: [
          new ObjectId("5d378db94e84753160e08b32"),
          new ObjectId("5d378db94e84753160e08b4a"),
          new ObjectId("5d378db94e84753160e08b4d")
        ]
      } 
    ];
    for (const quote of quotes) {
      await db.quotes.insertOne(quote);
    }

    for (const user of users) {
      await db.users.insertOne(user);
    }

    for (const bookmark of bookmarkings) {
      await db.bookmarkings.insertOne(bookmark);
    }
    
    console.log(`[seed]: success`)
  } catch (error) {
    throw new Error(`Failed to seed Database: ${error}`)
  }
}

seed();